export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REFRESH_ACCESS_REQUEST = 'REFRESH_ACCESS_REQUEST'
export const REFRESH_ACCESS_SUCCESS = 'REFRESH_ACCESS_SUCCESS'
export const REFRESH_ACCESS_FAIL = 'REFRESH_ACCESS_FAIL'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'