export const ALL_TECHNICIANS_REQUEST = 'ALL_TECHNICIANS_REQUEST'
export const ALL_TECHNICIANS_SUCCESS = 'ALL_TECHNICIANS_SUCCESS'
export const ALL_TECHNICIANS_FAIL = 'ALL_TECHNICIANS_FAIL'

export const CREATE_TECHNICIAN_REQUEST = 'CREATE_TECHNICIAN_REQUEST'
export const CREATE_TECHNICIAN_SUCCESS = 'CREATE_TECHNICIAN_SUCCESS'
export const CREATE_TECHNICIAN_RESET = 'CREATE_TECHNICIAN_RESET'
export const CREATE_TECHNICIAN_FAIL = 'CREATE_TECHNICIAN_FAIL'

export const UPDATE_TECHNICIAN_REQUEST = 'UPDATE_TECHNICIAN_REQUEST'
export const UPDATE_TECHNICIAN_SUCCESS = 'UPDATE_TECHNICIAN_SUCCESS'
export const UPDATE_TECHNICIAN_RESET = 'UPDATE_TECHNICIAN_RESET'
export const UPDATE_TECHNICIAN_FAIL = 'UPDATE_TECHNICIAN_FAIL'

export const DELETE_TECHNICIAN_REQUEST = 'DELETE_TECHNICIAN_REQUEST'
export const DELETE_TECHNICIAN_SUCCESS = 'DELETE_TECHNICIAN_SUCCESS'
export const DELETE_TECHNICIAN_RESET = 'DELETE_TECHNICIAN_RESET'
export const DELETE_TECHNICIAN_FAIL = 'DELETE_TECHNICIAN_FAIL'

export const TECHNICIAN_DETAILS_REQUEST = 'TECHNICIAN_DETAILS_REQUEST'
export const TECHNICIAN_DETAILS_SUCCESS = 'TECHNICIAN_DETAILS_SUCCESS'
export const TECHNICIAN_DETAILS_FAIL = 'TECHNICIAN_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'